import os
from io import BytesIO
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, KeepTogether
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Custom canvas that tracks pages and draws headers/footers with 'Page X of Y'."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []
        self.session_role = "Candidate"
        self.session_level = ""
        self.session_date = ""

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        
        # Color definitions
        primary_color = colors.HexColor("#6366F1")  # Indigo
        text_muted = colors.HexColor("#94A3B8")     # Slate Gray
        border_color = colors.HexColor("#E2E8F0")   # Light gray
        
        # Don't draw top header on the first page, just footer
        if self._pageNumber > 1:
            # Running Header
            self.setFont("Helvetica-Bold", 8)
            self.setFillColor(primary_color)
            self.drawString(54, 755, "PREPORA AI")
            self.setFont("Helvetica", 8)
            self.setFillColor(colors.HexColor("#1E293B"))
            self.drawString(115, 755, f"|   {self.session_level} {self.session_role} Interview Report")
            self.drawRightString(612 - 54, 755, self.session_date)
            
            # Header rule
            self.setStrokeColor(border_color)
            self.setLineWidth(0.5)
            self.line(54, 747, 612 - 54, 747)

        # Running Footer (on all pages)
        self.setStrokeColor(border_color)
        self.setLineWidth(0.5)
        self.line(54, 50, 612 - 54, 50)
        
        self.setFont("Helvetica", 8)
        self.setFillColor(text_muted)
        self.drawString(54, 38, "Confidential  •  Generated by Prepora AI Interview Coach")
        self.drawRightString(612 - 54, 38, f"Page {self._pageNumber} of {page_count}")
        
        self.restoreState()

def generate_pdf_report(session_data: dict) -> BytesIO:
    """Generate a clean and premium interview performance PDF using ReportLab."""
    buffer = BytesIO()
    
    # Page setup - Letter, 0.75-inch (54pt) margins
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=54,
        bottomMargin=64
    )
    
    story = []
    styles = getSampleStyleSheet()
    
    # Custom styles
    # Primary colors
    c_primary = colors.HexColor("#6366F1")    # Indigo
    c_text_main = colors.HexColor("#1E293B")  # Dark Slate
    c_bg_light = colors.HexColor("#F8FAFC")   # Soft Slate
    c_success = colors.HexColor("#10B981")    # Green
    c_warning = colors.HexColor("#F59E0B")    # Amber
    c_error = colors.HexColor("#EF4444")      # Red
    
    # Modify default styles or create custom ones
    styles.add(ParagraphStyle(
        name="DocTitle",
        fontName="Helvetica-Bold",
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#0F172A"),
        spaceAfter=4
    ))
    styles.add(ParagraphStyle(
        name="DocSubtitle",
        fontName="Helvetica",
        fontSize=11,
        leading=14,
        textColor=colors.HexColor("#475569"),
        spaceAfter=15
    ))
    styles.add(ParagraphStyle(
        name="ScoreLabel",
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=12,
        textColor=colors.HexColor("#475569"),
        alignment=1  # Center
    ))
    styles.add(ParagraphStyle(
        name="ScoreNum",
        fontName="Helvetica-Bold",
        fontSize=28,
        leading=32,
        textColor=c_primary,
        alignment=1  # Center
    ))
    styles.add(ParagraphStyle(
        name="SectionHeading",
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#0F172A"),
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    ))
    styles.add(ParagraphStyle(
        name="CardText",
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=c_text_main
    ))
    styles.add(ParagraphStyle(
        name="CardHeader",
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=13,
        textColor=c_text_main
    ))
    styles.add(ParagraphStyle(
        name="LabelBold",
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=11,
        textColor=colors.HexColor("#475569")
    ))
    styles.add(ParagraphStyle(
        name="LabelValue",
        fontName="Helvetica",
        fontSize=9.5,
        leading=11,
        textColor=c_text_main
    ))
    styles.add(ParagraphStyle(
        name="QNumber",
        fontName="Helvetica-Bold",
        fontSize=11,
        leading=14,
        textColor=c_primary,
        spaceBefore=8,
        keepWithNext=True
    ))
    styles.add(ParagraphStyle(
        name="QText",
        fontName="Helvetica-Bold",
        fontSize=10.5,
        leading=14,
        textColor=colors.HexColor("#0F172A"),
        keepWithNext=True
    ))
    styles.add(ParagraphStyle(
        name="TranscriptText",
        fontName="Helvetica",
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor("#334155")
    ))
    styles.add(ParagraphStyle(
        name="CritiqueBox",
        fontName="Helvetica-Oblique",
        fontSize=9.5,
        leading=13,
        textColor=colors.HexColor("#475569")
    ))

    # Parse and format Date
    created_at = session_data.get("created_at")
    if isinstance(created_at, str):
        try:
            dt = datetime.fromisoformat(created_at.replace("Z", "+00:00"))
            date_str = dt.strftime("%B %d, %Y")
        except ValueError:
            date_str = created_at
    elif isinstance(created_at, datetime):
        date_str = created_at.strftime("%B %d, %Y")
    else:
        date_str = datetime.utcnow().strftime("%B %d, %Y")

    role = session_data.get("role", "Software Engineer")
    level = session_data.get("level", "Mid-level")
    overall_score = session_data.get("overall_score", 0)
    
    # ------------------ HEADER SECTOR ------------------
    # Prepora Header Table layout
    header_data = [
        [
            Paragraph("PREPORA", ParagraphStyle(name="Brand", fontName="Helvetica-Bold", fontSize=12, leading=14, textColor=c_primary)),
            ""
        ],
        [
            Paragraph(f"{level} {role} Interview", styles["DocTitle"]),
            # Score card container
            Table(
                [
                    [Paragraph("OVERALL SCORE", styles["ScoreLabel"])],
                    [Paragraph(f"{overall_score / 10:.1f}/10", styles["ScoreNum"])]
                ],
                colWidths=[120],
                style=TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#EEF2F6")),
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                    ('TOPPADDING', (0,0), (-1,-1), 8),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                    ('ALIGN', (0,0), (-1,-1), 'CENTER'),
                    ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E1")),
                ])
            )
        ],
        [
            Paragraph(f"Session performance scorecard generated on {date_str}.", styles["DocSubtitle"]),
            ""
        ]
    ]
    
    header_table = Table(header_data, colWidths=[384, 120])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('SPAN', (0,0), (1,0)), # Span brand name across columns
        ('SPAN', (0,2), (1,2)), # Span subtitle across columns
        ('SPAN', (1,1), (1,1)), # Score table
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    
    story.append(header_table)
    story.append(Spacer(1, 10))

    # ------------------ METRICS TABLE ------------------
    # Display the score breakdown
    t_score = session_data.get("technical_score", 0) or 0
    c_score = session_data.get("communication_score", 0) or 0
    p_score = session_data.get("problem_solving_score", 0) or 0
    s_score = session_data.get("structure_score", 0) or 0

    def get_rating_color(score):
        if score >= 80: return c_success
        if score >= 60: return c_warning
        return c_error

    metrics_table_data = [
        [
            Paragraph("Technical Accuracy", styles["LabelBold"]),
            Paragraph(f"{t_score / 10:.1f}/10", ParagraphStyle(name="S1", parent=styles["LabelValue"], fontName="Helvetica-Bold", textColor=get_rating_color(t_score))),
            Paragraph("Communication Clarity", styles["LabelBold"]),
            Paragraph(f"{c_score / 10:.1f}/10", ParagraphStyle(name="S2", parent=styles["LabelValue"], fontName="Helvetica-Bold", textColor=get_rating_color(c_score)))
        ],
        [
            Paragraph("Problem Solving Depth", styles["LabelBold"]),
            Paragraph(f"{p_score / 10:.1f}/10", ParagraphStyle(name="S3", parent=styles["LabelValue"], fontName="Helvetica-Bold", textColor=get_rating_color(p_score))),
            Paragraph("Answer Structure (STAR)", styles["LabelBold"]),
            Paragraph(f"{s_score / 10:.1f}/10", ParagraphStyle(name="S4", parent=styles["LabelValue"], fontName="Helvetica-Bold", textColor=get_rating_color(s_score)))
        ]
    ]

    metrics_table = Table(metrics_table_data, colWidths=[140, 112, 140, 112])
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), c_bg_light),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 10),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E1")),
    ]))

    story.append(metrics_table)
    story.append(Spacer(1, 15))

    # ------------------ SUMMARY ------------------
    summary_text = session_data.get("feedback_summary", "No summary provided.")
    summary_flowables = [
        Paragraph("EXECUTIVE SUMMARY", styles["SectionHeading"]),
        Paragraph(summary_text, ParagraphStyle(name="SummaryText", fontName="Helvetica", fontSize=10, leading=15, textColor=c_text_main)),
        Spacer(1, 12)
    ]
    story.extend(summary_flowables)

    # ------------------ STRENGTHS & WEAKNESSES ------------------
    strengths = session_data.get("strengths", []) or []
    weaknesses = session_data.get("weaknesses", []) or []

    strengths_html = "".join([f"• {s}<br/><br/>" for s in strengths]).strip("<br/><br/>")
    weaknesses_html = "".join([f"• {w}<br/><br/>" for w in weaknesses]).strip("<br/><br/>")

    sw_table_data = [
        [
            Paragraph("KEY STRENGTHS", ParagraphStyle(name="GreenH", parent=styles["CardHeader"], textColor=colors.HexColor("#065F46"))),
            Paragraph("AREAS FOR IMPROVEMENT", ParagraphStyle(name="RedH", parent=styles["CardHeader"], textColor=colors.HexColor("#991B1B")))
        ],
        [
            Paragraph(strengths_html if strengths_html else "No key strengths noted.", styles["CardText"]),
            Paragraph(weaknesses_html if weaknesses_html else "No key weaknesses noted.", styles["CardText"])
        ]
    ]

    sw_table = Table(sw_table_data, colWidths=[246, 246])
    sw_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor("#ECFDF5")),  # Green tint for strengths
        ('BACKGROUND', (1,0), (1,-1), colors.HexColor("#FEF2F2")),  # Red tint for weaknesses
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('PADDING', (0,0), (-1,-1), 12),
        ('INNERGRID', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
        ('BOX', (0,0), (-1,-1), 1, colors.HexColor("#CBD5E1")),
    ]))

    story.append(sw_table)
    story.append(Spacer(1, 20))
    story.append(PageBreak())  # Force transcript to start on page 2

    # ------------------ DETAILED TRANSCRIPT ------------------
    story.append(Paragraph("DETAILED TRANSCRIPT & FEEDBACK", styles["SectionHeading"]))
    story.append(Spacer(1, 5))

    questions = session_data.get("questions", []) or []
    questions_sorted = sorted(questions, key=lambda x: x.get("question_order", 0))

    for idx, q in enumerate(questions_sorted):
        q_num = idx + 1
        q_text = q.get("question_text", "No question text.")
        u_ans = q.get("user_answer") or "[Answer skipped or empty]"
        critique = q.get("critique") or "No critique provided."
        q_score = q.get("score", 0) or 0
        model_ans = q.get("model_answer") or "No model answer provided."

        # QA Card container
        qa_flowables = [
            Paragraph(f"QUESTION {q_num}", styles["QNumber"]),
            Paragraph(q_text, styles["QText"]),
            Spacer(1, 6),
            Paragraph(f"<b>Candidate Response:</b> {u_ans}", styles["TranscriptText"]),
            Spacer(1, 6),
        ]

        # Score & Critique Box
        critique_title = Paragraph(f"<b>AI Review Score: <font color='{get_rating_color(q_score).hexval()}'>{q_score / 10:.1f}/10</font></b>", styles["CardHeader"])
        critique_body = Paragraph(critique, styles["CritiqueBox"])
        
        critique_table = Table([[critique_title], [critique_body]], colWidths=[488])
        critique_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F1F5F9")),
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('PADDING', (0,0), (-1,-1), 8),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#E2E8F0")),
        ]))
        qa_flowables.append(critique_table)
        qa_flowables.append(Spacer(1, 8))

        # Model Answer Box
        model_title = Paragraph("<b>MODEL ANSWER BENCHMARK</b>", ParagraphStyle(name="MH", parent=styles["CardHeader"], fontSize=8.5, textColor=colors.HexColor("#475569")))
        model_body = Paragraph(model_ans, ParagraphStyle(name="MB", fontName="Helvetica", fontSize=9, leading=13, textColor=colors.HexColor("#475569")))
        
        model_table = Table([[model_title], [model_body]], colWidths=[488])
        model_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#FAF5FF")), # Light violet background
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('PADDING', (0,0), (-1,-1), 8),
            ('BOX', (0,0), (-1,-1), 0.5, colors.HexColor("#E0F2FE")),
        ]))
        
        qa_flowables.append(model_table)
        qa_flowables.append(Spacer(1, 15))

        # Render questions in cohesive blocks
        story.append(KeepTogether(qa_flowables))

    # Callback to dynamically pass session details to NumberedCanvas for header render
    def on_build_start(canvas_instance, doc_instance):
        canvas_instance.session_role = role
        canvas_instance.session_level = level
        canvas_instance.session_date = date_str

    doc.build(story, canvasmaker=NumberedCanvas, onFirstPage=lambda c, d: on_build_start(c, doc), onLaterPages=lambda c, d: on_build_start(c, doc))
    
    buffer.seek(0)
    return buffer

if __name__ == "__main__":
    # Test compilation
    test_session = {
        "role": "Frontend Developer",
        "level": "Senior",
        "created_at": datetime.utcnow().isoformat(),
        "overall_score": 88,
        "technical_score": 90,
        "communication_score": 85,
        "problem_solving_score": 87,
        "structure_score": 90,
        "feedback_summary": "Overall a very solid frontend interview. The candidate demonstrates deep expertise in web vitals, optimization patterns, and React architecture. Communication is structured and uses STAR methodology, but they can quantify outcomes more.",
        "strengths": ["Clear technical depth in Core Web Vitals optimization.", "Structured STAR method usage.", "Deep knowledge of browser rendering engine mechanics."],
        "weaknesses": ["Missed opportunities to quantify metric improvements.", "Could discuss offline support patterns in more detail."],
        "questions": [
            {
                "question_order": 1,
                "question_text": "How do you optimize Largest Contentful Paint (LCP) for an image-heavy landing page?",
                "user_answer": "I would optimize LCP by prioritizing the loading of critical images. Using things like fetchpriority high on the main hero image, compressing assets with modern formats like webp, and preloading key images in the HTML head.",
                "critique": "A very strong response covering fetchpriority and preload tags. You successfully addressed modern performance patterns. Consider listing actual metric thresholds (e.g. LCP should be under 2.5s) to prove operational precision.",
                "score": 92,
                "model_answer": "Optimizing LCP starts with identifying the LCP element. For image elements, apply fetchpriority='high' directly to instruct the browser to load it before general script bundles. Combine this with responsive images (srcset) and AVIF/WebP formats, lazy-loading offscreen images, and setting DNS prefetch or preconnect to CDN assets. This should easily achieve the target LCP under 2.5 seconds."
            }
        ]
    }
    
    pdf_buffer = generate_pdf_report(test_session)
    with open("test_report.pdf", "wb") as f:
        f.write(pdf_buffer.read())
    print("Test PDF generated successfully as test_report.pdf")
